# Database connection
[postgres]
host = "ep-young-sound-a5fmuzwl.us-east-2.aws.neon.tech"
port = 5432
database = "finance_data"
user = "neondb_owner"
password = "uqAcYd9sF3xl"

# Other secrets
SECRET_KEY = "docilworks-secret-key-2024"
